openapi: 3.2.0
info:
  title: Vision Tools Metrics API
  version: 0.1.0
servers:
- url: https://api.va.landing.ai
  description: Production vision tools API
tags:
- name: Metrics
paths:
  /metrics:
    get:
      summary: Metrics
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
      - Basic Auth: []
      tags:
      - Metrics
components:
  securitySchemes:
    Basic_Auth:
      type: http
      description: 'Your unique API key for authentication.


        Get your API key here: https://va.landing.ai/settings/api-key.


        If using the EU endpoint, get your API key here: https://va.eu-west-1.landing.ai/settings/api-key.'
      scheme: bearer
      bearerFormat: Basic
